# Site title and description
title:              HIBK?
description:        Check if your coins are under surveillance and counter with obfuscation.

# Site subpath, e.g. /blog
baseurl:            ""

# Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
permalink:          /:title/

# Site base hostname & protocol, e.g. http://example.com
url:                "https://haveibeenknown.com"

# Site logo, dark and light depending on page hero text setting dark/light
logo_image:
    light:          logo-light.svg  # e.g. logo.png, upload logo image file to /assets/posts/ folder
    dark:           logo-dark.svg  # e.g. logo.png, upload logo image file to /assets/posts/ folder

# Author settings, displayed on about page
author:
    github:			https://github.com/satoshua/haveibeenknown

# Social share buttons
twitter_username:   satoshua
github_username:    satoshua

# Default footer image settings
footer:
    copyright:      Made by <a href="https://twitter.com/satoshua">Satoshua</a> in Sydney, Australia.

# Path to post content assets directory i.e post images, pdfs etc
post_assets:        /assets/posts/

# Build settings
markdown:           kramdown
highlighter:        rouge

gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

sass:
  style:            compressed

collections:
  faqs:
    output: false

theme: jekyll-theme-cayman
